export const GET_MOVIE_PENDING = 'GET_MOVIE_PENDING';
export const GET_MOVIE_FULFILLED = 'GET_MOVIE_FULFILLED';
export const GET_MOVIE_REJECTED = 'GET_MOVIE_REJECTED';
export const GET_MOVIE_DETAIL_PENDING = 'GET_MOVIE_DETAIL_PENDING';
export const GET_MOVIE_DETAIL_FULFILLED = 'GET_MOVIE_DETAIL_FULFILLED';
export const GET_MOVIE_DETAIL_REJECTED = 'GET_MOVIE_DETAIL_REJECTED';

