export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const SET_SEARCH_YEAR = "SET_SEARCH_YEAR";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const SET_SEARCH_PAGE = "SET_SEARCH_PAGE";
export const RESET_SEARCH_STATE = "RESET_SEARCH_STATE";